TYPE=VIEW
query=select `m`.`month_start` AS `month_start`,coalesce((select count(0) from `spa_crm_mis`.`appointments` `a` where date_format(`a`.`appointment_start`,\'%Y-%m-01\') = `m`.`month_start`),0) AS `total_appointments`,coalesce((select count(0) from `spa_crm_mis`.`service_sessions` `ss` where date_format(`ss`.`session_date`,\'%Y-%m-01\') = `m`.`month_start` and `ss`.`status` = \'COMPLETED\'),0) AS `completed_sessions`,coalesce((select sum(`p`.`amount`) from `spa_crm_mis`.`payments` `p` where date_format(`p`.`payment_date`,\'%Y-%m-01\') = `m`.`month_start` and `p`.`payment_status` = \'PAID\'),0) AS `cash_collected`,coalesce((select sum(`ss`.`actual_price`) from `spa_crm_mis`.`service_sessions` `ss` where date_format(`ss`.`session_date`,\'%Y-%m-01\') = `m`.`month_start` and `ss`.`status` = \'COMPLETED\'),0) AS `actual_revenue`,coalesce((select sum(`c`.`commission_amount`) from (`spa_crm_mis`.`commissions` `c` join `spa_crm_mis`.`service_sessions` `ss` on(`c`.`session_id` = `ss`.`session_id`)) where date_format(`ss`.`session_date`,\'%Y-%m-01\') = `m`.`month_start`),0) AS `total_commission` from (select distinct date_format(`spa_crm_mis`.`service_sessions`.`session_date`,\'%Y-%m-01\') AS `month_start` from `spa_crm_mis`.`service_sessions` union select distinct date_format(`spa_crm_mis`.`payments`.`payment_date`,\'%Y-%m-01\') AS `month_start` from `spa_crm_mis`.`payments` union select distinct date_format(`spa_crm_mis`.`appointments`.`appointment_start`,\'%Y-%m-01\') AS `month_start` from `spa_crm_mis`.`appointments`) `m`
md5=40b67cde35e47233d27b198931d2531b
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001782244009084798
create-version=2
source=SELECT\n    m.month_start,\n\n    COALESCE((\n        SELECT COUNT(*)\n        FROM appointments a\n        WHERE DATE_FORMAT(a.appointment_start, \'%Y-%m-01\') = m.month_start\n    ), 0) AS total_appointments,\n\n    COALESCE((\n        SELECT COUNT(*)\n        FROM service_sessions ss\n        WHERE DATE_FORMAT(ss.session_date, \'%Y-%m-01\') = m.month_start\n          AND ss.status = \'COMPLETED\'\n    ), 0) AS completed_sessions,\n\n    COALESCE((\n        SELECT SUM(amount)\n        FROM payments p\n        WHERE DATE_FORMAT(p.payment_date, \'%Y-%m-01\') = m.month_start\n          AND p.payment_status = \'PAID\'\n    ), 0) AS cash_collected,\n\n    COALESCE((\n        SELECT SUM(actual_price)\n        FROM service_sessions ss\n        WHERE DATE_FORMAT(ss.session_date, \'%Y-%m-01\') = m.month_start\n          AND ss.status = \'COMPLETED\'\n    ), 0) AS actual_revenue,\n\n    COALESCE((\n        SELECT SUM(commission_amount)\n        FROM commissions c\n        JOIN service_sessions ss ON c.session_id = ss.session_id\n        WHERE DATE_FORMAT(ss.session_date, \'%Y-%m-01\') = m.month_start\n    ), 0) AS total_commission\n\nFROM (\n    SELECT DISTINCT DATE_FORMAT(session_date, \'%Y-%m-01\') AS month_start\n    FROM service_sessions\n\n    UNION\n\n    SELECT DISTINCT DATE_FORMAT(payment_date, \'%Y-%m-01\') AS month_start\n    FROM payments\n\n    UNION\n\n    SELECT DISTINCT DATE_FORMAT(appointment_start, \'%Y-%m-01\') AS month_start\n    FROM appointments\n) m
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_uca1400_ai_ci
view_body_utf8=select `m`.`month_start` AS `month_start`,coalesce((select count(0) from `spa_crm_mis`.`appointments` `a` where date_format(`a`.`appointment_start`,\'%Y-%m-01\') = `m`.`month_start`),0) AS `total_appointments`,coalesce((select count(0) from `spa_crm_mis`.`service_sessions` `ss` where date_format(`ss`.`session_date`,\'%Y-%m-01\') = `m`.`month_start` and `ss`.`status` = \'COMPLETED\'),0) AS `completed_sessions`,coalesce((select sum(`p`.`amount`) from `spa_crm_mis`.`payments` `p` where date_format(`p`.`payment_date`,\'%Y-%m-01\') = `m`.`month_start` and `p`.`payment_status` = \'PAID\'),0) AS `cash_collected`,coalesce((select sum(`ss`.`actual_price`) from `spa_crm_mis`.`service_sessions` `ss` where date_format(`ss`.`session_date`,\'%Y-%m-01\') = `m`.`month_start` and `ss`.`status` = \'COMPLETED\'),0) AS `actual_revenue`,coalesce((select sum(`c`.`commission_amount`) from (`spa_crm_mis`.`commissions` `c` join `spa_crm_mis`.`service_sessions` `ss` on(`c`.`session_id` = `ss`.`session_id`)) where date_format(`ss`.`session_date`,\'%Y-%m-01\') = `m`.`month_start`),0) AS `total_commission` from (select distinct date_format(`spa_crm_mis`.`service_sessions`.`session_date`,\'%Y-%m-01\') AS `month_start` from `spa_crm_mis`.`service_sessions` union select distinct date_format(`spa_crm_mis`.`payments`.`payment_date`,\'%Y-%m-01\') AS `month_start` from `spa_crm_mis`.`payments` union select distinct date_format(`spa_crm_mis`.`appointments`.`appointment_start`,\'%Y-%m-01\') AS `month_start` from `spa_crm_mis`.`appointments`) `m`
sql_path=CURRENT_SCHEMA
mariadb-version=120302
