TYPE=VIEW
query=select `cp`.`customer_package_id` AS `customer_package_id`,`c`.`full_name` AS `customer_name`,`p`.`package_name` AS `package_name`,`cp`.`purchase_date` AS `purchase_date`,`cp`.`expiry_date` AS `expiry_date`,`cp`.`purchase_amount` AS `purchase_amount`,`cp`.`paid_amount` AS `paid_amount`,coalesce((select sum(`ss`.`actual_price`) from `spa_crm_mis`.`service_sessions` `ss` where `ss`.`customer_package_id` = `cp`.`customer_package_id` and `ss`.`status` = \'COMPLETED\'),0) AS `actual_revenue`,`cp`.`paid_amount` - coalesce((select sum(`ss`.`actual_price`) from `spa_crm_mis`.`service_sessions` `ss` where `ss`.`customer_package_id` = `cp`.`customer_package_id` and `ss`.`status` = \'COMPLETED\'),0) AS `unearned_revenue`,coalesce((select sum(`cpi`.`total_sessions`) from `spa_crm_mis`.`customer_package_items` `cpi` where `cpi`.`customer_package_id` = `cp`.`customer_package_id`),0) AS `total_sessions`,coalesce((select sum(`cpi`.`used_sessions`) from `spa_crm_mis`.`customer_package_items` `cpi` where `cpi`.`customer_package_id` = `cp`.`customer_package_id`),0) AS `used_sessions`,coalesce((select sum(`cpi`.`remaining_sessions`) from `spa_crm_mis`.`customer_package_items` `cpi` where `cpi`.`customer_package_id` = `cp`.`customer_package_id`),0) AS `remaining_sessions`,`cp`.`status` AS `status` from ((`spa_crm_mis`.`customer_packages` `cp` join `spa_crm_mis`.`customers` `c` on(`cp`.`customer_id` = `c`.`customer_id`)) join `spa_crm_mis`.`packages` `p` on(`cp`.`package_id` = `p`.`package_id`))
md5=9cd5a50f508c5ca51eea91971f2f77ae
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001782244009075661
create-version=2
source=SELECT\n    cp.customer_package_id,\n    c.full_name AS customer_name,\n    p.package_name,\n    cp.purchase_date,\n    cp.expiry_date,\n    cp.purchase_amount,\n    cp.paid_amount,\n\n    COALESCE((\n        SELECT SUM(ss.actual_price)\n        FROM service_sessions ss\n        WHERE ss.customer_package_id = cp.customer_package_id\n          AND ss.status = \'COMPLETED\'\n    ), 0) AS actual_revenue,\n\n    cp.paid_amount - COALESCE((\n        SELECT SUM(ss.actual_price)\n        FROM service_sessions ss\n        WHERE ss.customer_package_id = cp.customer_package_id\n          AND ss.status = \'COMPLETED\'\n    ), 0) AS unearned_revenue,\n\n    COALESCE((\n        SELECT SUM(cpi.total_sessions)\n        FROM customer_package_items cpi\n        WHERE cpi.customer_package_id = cp.customer_package_id\n    ), 0) AS total_sessions,\n\n    COALESCE((\n        SELECT SUM(cpi.used_sessions)\n        FROM customer_package_items cpi\n        WHERE cpi.customer_package_id = cp.customer_package_id\n    ), 0) AS used_sessions,\n\n    COALESCE((\n        SELECT SUM(cpi.remaining_sessions)\n        FROM customer_package_items cpi\n        WHERE cpi.customer_package_id = cp.customer_package_id\n    ), 0) AS remaining_sessions,\n\n    cp.status\nFROM customer_packages cp\nJOIN customers c ON cp.customer_id = c.customer_id\nJOIN packages p ON cp.package_id = p.package_id
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_uca1400_ai_ci
view_body_utf8=select `cp`.`customer_package_id` AS `customer_package_id`,`c`.`full_name` AS `customer_name`,`p`.`package_name` AS `package_name`,`cp`.`purchase_date` AS `purchase_date`,`cp`.`expiry_date` AS `expiry_date`,`cp`.`purchase_amount` AS `purchase_amount`,`cp`.`paid_amount` AS `paid_amount`,coalesce((select sum(`ss`.`actual_price`) from `spa_crm_mis`.`service_sessions` `ss` where `ss`.`customer_package_id` = `cp`.`customer_package_id` and `ss`.`status` = \'COMPLETED\'),0) AS `actual_revenue`,`cp`.`paid_amount` - coalesce((select sum(`ss`.`actual_price`) from `spa_crm_mis`.`service_sessions` `ss` where `ss`.`customer_package_id` = `cp`.`customer_package_id` and `ss`.`status` = \'COMPLETED\'),0) AS `unearned_revenue`,coalesce((select sum(`cpi`.`total_sessions`) from `spa_crm_mis`.`customer_package_items` `cpi` where `cpi`.`customer_package_id` = `cp`.`customer_package_id`),0) AS `total_sessions`,coalesce((select sum(`cpi`.`used_sessions`) from `spa_crm_mis`.`customer_package_items` `cpi` where `cpi`.`customer_package_id` = `cp`.`customer_package_id`),0) AS `used_sessions`,coalesce((select sum(`cpi`.`remaining_sessions`) from `spa_crm_mis`.`customer_package_items` `cpi` where `cpi`.`customer_package_id` = `cp`.`customer_package_id`),0) AS `remaining_sessions`,`cp`.`status` AS `status` from ((`spa_crm_mis`.`customer_packages` `cp` join `spa_crm_mis`.`customers` `c` on(`cp`.`customer_id` = `c`.`customer_id`)) join `spa_crm_mis`.`packages` `p` on(`cp`.`package_id` = `p`.`package_id`))
sql_path=CURRENT_SCHEMA
mariadb-version=120302
